name: Lab_RekanKerjaku_FrontEnd
description: Your starter kit business.

authors:
  - Fadhil <1996.fadhli@gmail.com>
homepage: https://rekankerjaku.com
version: 1.0+1
maintainer: Fadhil @git-maspaad

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  benchmark_harness: ^1.0.5
  crypto: ^2.1.4
  cryptoutils: ^0.4.0
  cupertino_icons: ^0.1.3
  fixnum: ^0.10.11
  flutter_inappbrowser: ^2.0.2
  http: ^0.12.0+4
  logging: ^0.11.4
  shared_preferences: ^0.5.6+3
  
  # start_jwt: ^0.2.0
  # start_jwt:
    # git: git@github.com:bsjung/start_jwt.git
    # git: https://github.com/bsjung/start_jwt.git
  
  # bignum:
  #   git: git://github.com/Dartist/dart-bignum.git
  # bignum: ^0.1.0
  # cipher2: ^0.3.5
  # flutter_cipher: ^0.0.3
  # pointycastle: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  asn1lib: ^0.5.15

flutter:
  uses-material-design: true

  assets:
    # JPG
    - images/img_wallpaper.jpg
    - images/img_wallpaper_AlgonquinGrouse.jpg
    - images/img_wallpaper_CharlestonAzaleas.jpg
    - images/img_wallpaper_FormentorHolidays.jpg
    - images/img_wallpaper_HimachalFalls.jpg
    - images/img_wallpaper_NBNMSipapu.jpg
    - images/img_wallpaper_NoCaliCoast.jpg
    - images/img_wallpaper_SpainBeeEaters.jpg
    - images/img_wallpaper_UnicornoftheSea.jpg
    - images/img_wallpaper_VanCherryBlossom.jpg
    - images/img_wallpaper_WatChaloem.jpg

    # PNG
    - images/img_flutterlogo.png
    - images/img_jasindo_company.png
    - images/img_jasindo_header.png
    - images/img_jasindo_logo.png
    - images/img_jasindo_partner.png
    - images/img_rekankerjaku_logo0.png
    - images/img_rekankerjaku_logo1.png
    - images/img_rekankerjaku_logo2.png
    - images/img_rekankerjaku_logo3.png
    - images/img_rekankerjaku_logo4.png
    - images/img_rekankerjaku_logo5.png
    - images/img_users_group_512px.png

  fonts:
    - family: FiraSans
      fonts:
      - asset: fonts/FiraSans-Regular.ttf
